### ISSUE TITLE
Mixin apply failed food-effects.mixins.json:MixinCakeBlock / Exception in Thread "main"

### ISSUE THREAD

**Issue by PhweeDev** [infernalexp/Food-Effects#1]
Crashed when trying to start the mod.

[debug.log](https://github.com/infernalexp/Food-Effects/files/7491237/debug.log)
[latest.log](https://github.com/infernalexp/Food-Effects/files/7491238/latest.log)

**Comment by Dariensg** [comment]
You seem to be using Forge version 36.2.9, which is the latest, but not recommended, version. Could you try running it with 36.2.0, the recommended version for 1.16.5 and see if the problem persists?

**Comment by PhweeDev** [comment]
Still doesn't work with 36.2.0

https://paste.gg/p/anonymous/5aee47c9077c45bb88bb994f8691fe7a

**Comment by Dariensg** [comment]
Thanks! We are looking into it and will keep you updated!

**Comment by Dariensg** [comment]
[foodeffects-1.16.5-1.0.0.zip](https://github.com/infernalexp/Food-Effects/files/7491255/foodeffects-1.16.5-1.0.0.zip)
Could you let me know if this jar fixes it? Sorry about that!

**Comment by PhweeDev** [comment]
It does work now. Thanks for fixing it! :D

I will be closing the paste.gg now.

**Comment by Dariensg** [comment]
I'll upload the fix to CurseForge in just a second! Thanks for reporting this!

**Comment by PhweeDev** [comment]
Anytime. Thank you and the devs for fixing it. 👍
