### ISSUE TITLE
Modded food items in the config breaks the mod in a strange way.

### ISSUE THREAD

**Issue by MattB70** [infernalexp/Food-Effects#5]
The new release (1.18.2-1.1.2) mostly fixes the issue of items being replaced in the config, but I still cannot get modded foods to work. I suppose there are a few possible reasons. The modded cakes I want to add are not extending cake and are being eaten using some unique method, which I suspect isn't the case. Or something about the way Food Effects handles detecting if a cake is eaten only works for specifically minecraft:cake. Strangely, while some of the default food included in the config such as minecraft:cookie and minecraft:rabbit_stew work fine after starting the game, the (unedited) minecraft:cake and minecraft:dried_kelp entries do not work. I also attempted to add a non-cake based food from another namespace (farmersdelight:fried_egg) which also did not work. Are other namespaces not supported yet?

Addressing the "mostly" fixed aspect, the config states the effect amplifier range is [0, 255], though putting a value larger than 100 is reset back to 100 after starting the game. I didn't find any other issues with entries being overwritten.

The config used for testing:
https://gist.github.com/MattB70/76d9036310adab1de856b7803c0287c3#file-foodeffects-1-1-2-modded-config

Note:
Keep in mind that my modpack currently does significant changes to the way Minecraft handles food, hunger, and health. It also includes per-release builds for Tinkers, The Aether, and The Twilight Forest for 1.18.2 which may cause issues (though I could not think of a reasonably possible one to use an example here). As always, as I do this testing in parallel with other pre-release mods, some behavior may be impossible to replicate and therefore this issue could never be solved gracefully. Thanks for your time. :)

**Comment by Dariensg** [comment]
Thank you for reporting this! It seems to be having some strange behavior. Some of us have it working no problem, while for others it is having the same issue as you are having. We are looking into it and hope to have it fixed within 24 hours! Thank you for your patience!

**Comment by nekomaster1000** [comment]
Hah! Funnily enough, I JUST tested it myself with the Farmer's Delight fried egg too! We'll try and resolve it as soon as possible 👍

**Comment by MattB70** [comment]
I'm sure this has been discovered already, but it seems like the some entries in the config work for me about half of the time (except for cakes), so the overarching bug is probably not system specific. It may be related to mod loading order.
